name: Javascript

on:
  workflow_dispatch:
  # Disabled - push:
  #   branches:
  #     - master
  #   tags:
  #     - "**"
  # Disabled - pull_request:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@c449d86cf33a2a6c7a4193264cc2578e2c3266d4 # pin@v4
        with:
          paths_ignore: '["crates/**"]'

  typescript:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install dependencies
        run: ./s/ci-install
      - name: Typescript
        run: ./s/tsc

  eslint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install dependencies
        run: ./s/ci-install
      - name: Lint JS
        run: ./s/eslint

  prettier:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install dependencies
        run: ./s/ci-install
      - name: Check Formatting
        run: ./s/prettier
